### ISSUE TITLE
issue with graphix and plain TeX

### ISSUE THREAD

**Issue by GHT54** [latex3/graphics-def#35]
!! Please fill out all sections after reading CONTRIBUTING guidelines (and remove lines starting with !!)

## Brief outline of the bug

updates of pdftex.def and dvips.def produce errors with plain TeX

## Minimal example showing the bug

\input eplain
\input graphicx
\beginpackages
\usepackage{color}
\endpackages
test
\end

## Log file (required) and possibly PDF file  

!! Use drag-and-drop  (remember: .log file is required) !!

[test-mnltx.log](https://github.com/latex3/graphics-def/files/9667832/test-mnltx.log)

**Comment by davidcarlisle** [comment]
@GHT54  the log you attached is showing the `\outer` error from #34, did you mean to show

```
Runaway definition?
->\egroup \errhelp {You're in trouble here.  Try typing  <return>  to\ETC.
! File ended while scanning definition of \reserved@a.
<inserted text> 
                }
l.6 t
     est
? 
```

?

which looks er, not quite right...

**Comment by davidcarlisle** [comment]
or even just

```
\input eplain

\beginpackages
\usepackage{color}
\endpackages
test
\end
```

In the update this week I made `\newdimen` non-outer temporarily in `color.tex` and `graphicx.tex`  but here you are using `eplain` to bypass that and load `color.sty` directly.

I think the only thing I could do here would be to make `\newdimen` permanently non-`\outer` in `miniltx.tex` which would be an improvement (`\outer` is not useful in most cases) but perhaps a bigger change than miniltx should make, it doesn't generally change plain tex commands.

The fix is as before, add

```
\expandafter\def\expandafter\newdimen\expandafter{\newdimen}
```
anywhere before loading color.

An alternative would be to class it as an `eplain` issue: eplain "knows" about the implied scope of `\beginpackages` ... `\endpackages` and could make `\newdimen` non outer in that range (@kberry ?)

**Comment by kberry** [comment]
Hi David - since LaTeX itself removes \outer from \new... (right?), I
think it would be completely sensible and useful for miniltx to do the
same.  I can't see any benefit to preserving their \outer-ness.

Granted Eplain could make them inner within \{begin,end}packages, I
think it's best addressed in miniltx - could help more people that way.

Ok? --thanks, karl.

**Comment by davidcarlisle** [comment]
OK I'll do that yes all the register allocations are non-outer since at least the start of 2e.  @kberry

**Comment by davidcarlisle** [comment]
The version of graphic-pln with the above commit is now on ctan, so closing here,
